### ISSUE TITLE
Swipe not working in delegated events

### ISSUE THREAD

**Issue by BillTheGoat** [benmajor/jQuery-Touch-Events#100]
Using the code from the demo locally, everything works. However, if I change (for example) 

`.on('swiperight', function(e) { console_log( 'swiperight', false ); })`

 to
`.on('swiperight', '#touch-zone', function(e) { console_log( 'swiperight', false ); })`

The singletap and taphold events work, the swipe, double tap, etc. do not. I saw an issue from 2013 where a fix for this was supposed to have been integrated into code, but I have verified  this in Chrome on android, in android webview/chromeview, and in firefox on windows 8.1.

 Adding 

`.on('touchmove', '#touch-zone', function(e) { console_log( 'touchmove', false ); })`

shows that touchmove events are being registered. 

**Most curiously, if I add:**

`.on('tapmove', '#touch-zone', function(e) { console_log( 'touchmove', false ); })`

(note tapmove and not touchmove) everything _works_. However, it only works if it is _before _the swipe etc. listeners in the chain.

**Comment by BillTheGoat** [comment]
Further info.

1. Double tap is actually not working even with that change...

2. This does not work:

`$(document.body).on('tapstart', '.class', function () {console.log('class tapstart'); })
    .on('tapend', '.class', function() {console.log('class tapend'); })
    .on('tap', '.class', function() {console.log('class tap'); })
    .on('tapmove', '.class', function() {console.log('class tapmove');})
    .on('swipe',".class", function(){
    // Do something
});`
 And I get an error in my log:

`Uncaught TypeError: ((o.event.special[g.origType] || (intermediate value)).handle || g.handler).apply is not a function -- From line 3 jquery.min.js`

However I can see the tapstart, tapend, tap, and tapmove events.

**Comment by benmajor** [comment]
There's a known issue about delegating events from the `document` object. (https://github.com/benmajor/jQuery-Touch-Events/issues/99). 

A quick fix until I can get to fix this with v2 (it won't be fixed before v2, since it's bad practice to delegate to `document` anyway -- you should use the closest static element really), is to delegate to `body`:

    $('body').on('tapstart', '.class', function () { });

**Comment by BillTheGoat** [comment]
Ben, that was a bit of a red herring--I had just temporarily changed to document.body to see if that made any difference. 

The original issue remains, which is there is no way to call swipe or double click in delegated events--even bound to body as in the demo.  I can reduce your demo to:

` $('body').on('tapmove', '#touch-zone', function() { }).on('swipe', '#touch-zone', function(e) { console_log( 'swipe', false ); });`

but it breaks if you remove tapmove--so I need to include tapmove on all my delegated events. I have not managed to make the delegated doubletap work at all yet. 

Also a separate problem that arises while troubleshooting this is that a dynamically added element as a direct child of <body> doesn't react to delegated events bound to body. The same code works if I append it to a child div.

**Comment by benmajor** [comment]
Ah, thanks for the clarification. I will look at resolving this in a new push.

**Comment by BillTheGoat** [comment]
Doubletap is working -- that was my fault. I had set the timeout really low and forgot. So this is just an inconvenience, since it is possible to get everything working. Thanks!

**Comment by benmajor** [comment]
Bill, thanks. Can I go ahead and close the issue now?

**Comment by BillTheGoat** [comment]
Sure. My only hesitation is that, because we need to add that tapmove, it is not clear what is happening and thus things are easy to break. Much appreciated!
